/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package progradleTest;

public class App {
    public String getGreeting() {
        return "Hello sum of 2 numbers";
    }

    public int addNumber(int a, int b){
       return a+b;
    }

    public static void main(String[] args){
        App a = new App();
        System.out.println(a.getGreeting() + a.addNumber(2,3));
    }
}
